services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: env.DB_USER
      POSTGRES_PASSWORD: env.DB_PASSWORD
      POSTGRES_DB: env.DB_NAME
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
